server:
  port: 9090
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/commont
  datasource:
      url: jdbc:mysql://localhost:3306/wild?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
#    dev:
#      url: jdbc:mysql://localhost:3306/backup?useUnicode=true&characterEncoding=utf-8
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#      static-path-pattern: /upload/**
      static-path-pattern: file/**
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    multipart:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/,file/

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapperLocations: classpath:***/*/*/*/*.xml
    # 开启驼峰命名转换，如：Table(create_time) -> Entity(createTime)。不需要我们关心怎么进行字段匹配，mybatis会自动识别`大写字母与下划线`
    map-underscore-to-camel-case: true


file:
  path: file\
#  uploadFolder: D://file/
#  staticAccessPath: /file/**

pagehelper:
  page-size-zero: true
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
